services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    command: --max_allowed_packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: tjee1234
      MYSQL_DATABASE: ticketflow
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    # MySQL이 쿼리를 받을 수 있는 상태인지 주기적으로 검사
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -ptjee1234 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  elasticsearch:
    image: elasticsearch:8.19.3
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 1g에서 512m로 낮춤 (컨테이너 메모리 부족 방지)
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  kibana:
    image: kibana:8.19.3
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  spring-boot-app:
    build: .
    container_name: ticketflow-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/ticketflow?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=tjee1234
      - ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      mysql:
        condition: service_healthy # MySQL이 건강할 때만 실행
      elasticsearch:
        condition: service_healthy

volumes:
  mysql-data:
  es-data: